# Generated by Django 4.1.4 on 2022-12-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajoutanimal',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
