# Generated by Django 4.1.4 on 2022-12-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ajoutanimal_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='publication',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.ajoutanimal'),
            preserve_default=False,
        ),
    ]
